eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
spring:
    data:
        elasticsearch:
            cluster-nodes: 193.112.92.27:54130,123.207.108.96:54130,193.112.6.116:54130
            cluster-name: elasticsearch-cluster
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://gz-cdb-7eu96t0t.sql.tencentcdb.com:62471/minibuyker-user?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
        username: root
        password: XCWWSL76wJFxgHN7JX7ysYT2fOeUZk4bvKgn&noJjJ*K7@q2$IX&i7v7
    mail:
        host: localhost
        port: 25
        username: null
        password: null
    thymeleaf:
        cache: true
    zipkin:
        base-url: http://localhost:9411
        enabled: false
        locator:
            discovery:
                enabled: true
server:
    port: 8081
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
jhipster:
    http:
        version: V_1_1
        cache:
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: 7e2ec72770c157aa671f05cc3879cd810569af8d
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: user@localhost
        base-url: http://my-server-url-to-change
    metrics:
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: user
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs:
            enabled: false
            report-frequency: 60
    logging:
        logstash:
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics:
            enabled: false


liquibase:
    contexts: dev
    enabled: false

application: null
