eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
spring:
    data:
        elasticsearch:
            cluster-nodes: 193.112.92.27:54130,123.207.108.96:54130,193.112.6.116:54130
            cluster-name: elasticsearch-cluster
    elasticsearch:
        jest:
            uris: http://119.29.223.161:8200
            read-timeout: 5000
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    redis:
        host: 127.0.0.1
        port: 6379
        password: redis123
        timeout: 1000
        pool:
            max-active: 8
            min-idle: 0
            max-idle: 8
            max-wait: -1
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/xshwd_order?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
        username: root
        password: 258
    mail:
        host: localhost
        port: 25
        username: null
        password: null
    thymeleaf:
        cache: true
    zipkin:
        base-url: http://localhost:9411
        enabled: false
        locator:
            discovery:
                enabled: true
server:
    port: 8088
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
jhipster:
    gateway:
        rate-limiting:
            enabled: false
        authorized-microservices-endpoints: # Access Control Policy, if left empty for a route, all endpoints will be accessible
            app1: /api # recommended prod configuration
    http:
        version: V_1_1
        cache:
            timeToLiveInDays: 1461
    cache: # Cache configuration
        hazelcast: # Hazelcast distributed cache
            time-to-live-seconds: 3600
            backup-count: 1
    security:
        authentication:
            jwt:
                secret: 7e2ec72770c157aa671f05cc3879cd810569af8d
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail:
        from: order@localhost
        base-url: http://my-server-url-to-change
    metrics:
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: order
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs:
            enabled: false
            report-frequency: 60
    logging:
        logstash:
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics:
            enabled: false


liquibase:
    contexts: dev
    enabled: false

application:
